library("flexdashboard")
library("rmarkdown")
#library(kableExtra)
#library("svglite")
library(pivottabler)
library(DT)
library("reactable")
#library("ggtext")
library(ggpubr)
#library(ggiraph)
#library(plotly)
#library(ggiraph)
render("dash.Rmd")

